@baseUrl = http://localhost:3000

GET {{baseUrl}}/check
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36

###
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "maria",
  "user_name": "maria",
  "email": "maria@unico.com",
  "password": "123"
}
###

POST {{baseUrl}}/auth
Content-Type: application/json

{
  "user_name": "maria",
  "email": "maria@unico.com",
  "password": "123"
}