@baseUrl = http://localhost:3000

@authToken =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbmNyeXB0ZWREYXRhIjp7Iml2IjoiNTI0ZGIxNWFiMTZlMTlkOTFhY2FhNWNjMTUxNjU2MjYiLCJjb250ZW50IjoiY2IifSwiaWF0IjoxNzYyOTcyMjU5LCJleHAiOjE3NjM1NzcwNTl9.gMaXVflDyNo4Q5DKsWhHRoH5GewzKcx9IjYxUU8cM60

###
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "user_name": "musk",
  "email": "musk@unico.com",
  "password": "1234"
}

###
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "elonmusk",
  "user_name": "musk",
  "email": "musk@unico.com",
  "password": "1234"
}

###
GET {{baseUrl}}/user-profile/7

###
PUT {{baseUrl}}/user
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Elon Musk",
  "bio": "esse aqui é adm"
}

###
DELETE {{baseUrl}}/user
Authorization: Bearer {{authToken}}




###
POST {{baseUrl}}/posts
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "description": "Este é o meu primeiro tweet!"
}

###
POST {{baseUrl}}/posts
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "type": "RETWEET",
  "original_post_id": 1
}

###
GET {{baseUrl}}/posts

###
GET {{baseUrl}}/posts/7

###
PUT {{baseUrl}}/posts/7
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "description": "Este é o meu post... editado!"
}

###
DELETE {{baseUrl}}/posts/5
Authorization: Bearer {{authToken}}





###
POST {{baseUrl}}/posts/7/like
Authorization: Bearer {{authToken}}

###
DELETE {{baseUrl}}/posts/7/like
Authorization: Bearer {{authToken}}

###
DELETE {{baseUrl}}/admin/posts/7
Authorization: Bearer {{authToken}}