@baseUrl = http://localhost:3000

@authToken =

###
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "user_name": "jonas",
  "email": "jonas@unico.com",
  "password": "123"
}

###
> {%
    const token = response.body.token;
    client.global.set("authToken", token);
    client.log("Token capturado pelo script: " + token);
    
%}

###
POST {{baseUrl}}/user
Content-Type: application/json

{
  "name": "maria",
  "user_name": "jonas",
  "email": "jonas@unico.com",
  "password": "123"
}

###
GET {{baseUrl}}/user-profile/1

###
PUT {{baseUrl}}/user
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Jonas (Editado2)",
  "bio": "Esta é minha nova biografia."
}

###
DELETE {{baseUrl}}/user
Authorization: Bearer {{authToken}}

### 
POST {{baseUrl}}/posts
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "description": "Este é o meu primeiro tweet!"
}

###
POST {{baseUrl}}/posts
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "type": "RETWEET",
  "original_post_id": 1
}

###
GET {{baseUrl}}/posts

###
GET {{baseUrl}}/posts/1

###
DELETE {{baseUrl}}/posts/1
Authorization: Bearer {{authToken}}