version: '3.8'

services:
  app:
    image: vsc-trilha-back-comp-313c3c988d34903d8781026a91421db89c1cc4b9af770c42ee823eccdf19c0a1
    build:
      dockerfile: /tmp/devcontainercli-root/container-features/0.80.0-1761327966304/Dockerfile-with-features
      context: /var/lib/docker/codespacemount/.persistedshare/empty-folder
      args:
        - BUILDKIT_INLINE_CACHE=1
        - _DEV_CONTAINERS_BASE_IMAGE=dev_container_auto_added_stage_label
        - _DEV_CONTAINERS_IMAGE_USER=root
        - _DEV_CONTAINERS_FEATURE_CONTENT_SOURCE=dev_container_feature_content_temp
      additional_contexts:
        - dev_containers_feature_content_source=/tmp/devcontainercli-root/container-features/0.80.0-1761327966304

